version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"  # Location of your workflows (usually root-level .github/workflows)
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
