name: Test Mockserver

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  test-mockserver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/pytest/requirements.txt

      - name: Run pytest tests
        run: |
          pytest tests/pytest/test_mockserver.py -v

      - name: Test summary
        if: success()
        run: |
          echo "✅ MockServer test passed!"
          echo "Successfully loaded mocks/polkadot-full-mock.json into MockServer container"
          echo "and verified system_name RPC method response."
